### ISSUE TITLE
Fix RTL issue

### ISSUE THREAD

**Issue by devpow112** [Brightspace/d2l-rubric#1846]
Wrong margin in RTL
![image](https://user-images.githubusercontent.com/9043211/162870773-195b82e7-ab5d-4293-a08b-c951ac20c457.png)

Correct in LTR
![image](https://user-images.githubusercontent.com/9043211/162870870-b2e04d36-d93b-4e48-b56b-b6ee96964b29.png)

**Comment by devpow112** [comment]
Also alignment of `Level achieved` and the rest if off in the LTR view. Should all be inline.

**Comment by imcdonald-d2l** [comment]
PR to fix the issue: https://github.com/Brightspace/d2l-rubric/pull/1854
